#include <SDL_opengl.h>
/*

PFNGLUSEPROGRAMPROC					glUseProgramObjectARB;
PFNGLLINKPROGRAMARBPROC				glLinkProgramARB;
PFNGLATTACHOBJECTARBPROC			glAttachObjectARB;
PFNGLCREATEPROGRAMOBJECTARBPROC		glCreateProgramObjectARB;
PFNGLCREATESHADEROBJECTARBPROC		glCreateShaderObjectARB;
PFNGLSHADERSOURCEARBPROC			glShaderSourceARB;
PFNGLCOMPILESHADERARBPROC			glCompileShaderARB;
PFNGLDELETEOBJECTARBPROC			glDeleteObjectARB;
PFNGLISSHADERPROC					glIsShader;
PFNGLGETSHADERINFOLOGPROC			glGetShaderInfoLog;
PFNGLGETPROGRAMINFOLOGPROC			glGetProgramInfoLog;
PFNGLUNIFORM1FARBPROC				glUniform1fARB;
PFNGLUNIFORM2FARBPROC				glUniform2fARB;
PFNGLUNIFORM1IARBPROC				glUniform1iARB;*/